### ISSUE TITLE
PluralKit Support

### ISSUE THREAD

**Issue by Oliver-makes-code** [devOS-Sanity-Edition/TeaBridge#7] opened 2023-01-13 02:13 UTC
It'd be neat if there was PluralKit support.
You can detect messages sent by PluralKit and relay them to Minecraft using PlruralKit's API (Documentation found here: https://pluralkit.me/api/)

**Comment by maximumpower55** [comment] 2023-01-13 02:17
I will look into this for v1.1.0

**Comment by maximumpower55** [comment] 2023-01-13 04:46
@Oliver-makes-code I have been able to make it so messages from PK webhooks are actually sent, but I haven't figured out how to not send the messages that are about to be proxied

**Comment by Oliver-makes-code** [comment] 2023-01-13 04:55
You can make a lookup to PK's API with the old message id and it'll return a valid message object if it was proxied

**Comment by maximumpower55** [comment] 2023-01-16 02:26
> You can make a lookup to PK's API with the old message id and it'll return a valid message object if it was proxied

The problem is the `MessageReceivedEvent` is invoked before the message is proxied

**Comment by maximumpower55** [comment] 2023-01-16 02:36
The only way I know of fixing this is somehow delaying the event until the message is proxied, and that's jank since that will add delay to normal messages

**Comment by maximumpower55** [comment] 2023-08-09 00:11
Forgot to close this earlier, this is now done.

**Closed as completed by maximumpower55** 2023-08-09 00:11 UTC
Labels: enhancement, Intertwined
