### ISSUE TITLE
Add a 'Server stopping' message

### ISSUE THREAD

**Issue by Jamalam360** [devOS-Sanity-Edition/TeaBridge#17] opened 2023-08-08 22:04 UTC
Self explanatory, identical to the server starting message but sent when the server is stopping. @maximumpower55 says this is implemented but I don't believe it is looking at [this](https://github.com/devOS-Sanity-Edition/TeaBridge/blob/0a2ecfe5426f2513d35a1adea4832ccef1cc688b/src/main/java/one/devos/nautical/teabridge/TeaBridge.java#L55)

**Comment by asoji** [comment] 2023-08-08 22:11
Gonna take a look at this super quick because the last time I've used it back earlier this year, it did have the server stop message, so this is interesting...

**Comment by asoji** [comment] 2023-08-08 22:22
If the current BlanketCon server is to be believed, it is working?

![image](https://github.com/devOS-Sanity-Edition/TeaBridge/assets/99072163/4f1498d5-2779-48ec-8503-472a2cf962c2)

**Comment by Jamalam360** [comment] 2023-08-08 23:09
Unless I'm understanding the code wrong, this is only sent when the game crashes

**Comment by asoji** [comment] 2023-08-08 23:24
There is a server *stopped* message, but there isn't a *stopping* one, if that's what you want then my bad.

https://github.com/devOS-Sanity-Edition/TeaBridge/assets/99072163/f60335fd-4799-4aa5-af6c-e3792d89dfb1

**Comment by maximumpower55** [comment] 2023-08-08 23:58
What's the point of this? this would only happen a few seconds before the server actually stops

**Comment by Jamalam360** [comment] 2023-08-09 08:03
@asoji neither are showing for me which I would consider a bug. I would like either of them.

@maximumpower55 as a server admin I'd like to be able to see when the server stops - if the server stops, auto updates, and fails to restart I would currently have no indication of that through Discord.

Note that it could fail to restart in a way that a crash report wouldn't be sent (e.g. packwiz failing)

**Comment by asoji** [comment] 2023-08-09 08:12
If I may ask, which version are you using? I'm using the one provided by the latest TeamCity build and it seems to work for me?

https://github.com/devOS-Sanity-Edition/TeaBridge/releases/tag/TC-Build-0a2ecfe5426f2513d35a1adea4832ccef1cc688b

**Comment by Jamalam360** [comment] 2023-08-09 08:47
1.2.0 on Modrinth

**Comment by asoji** [comment] 2023-08-09 09:19
Weeeeird... that one should be working? All I can think of is regenerate your config and redownload the mod and try again?

**Comment by maximumpower55** [comment] 2023-08-09 10:19
The server stop message works fine for me, and this message is kinda useless, I'll be closing this since I can't reproduce. Best chance you have is to delete and recreate your config

**Comment by maximumpower55** [comment] 2023-08-09 10:20
Feel free to reopen

**Closed as completed by maximumpower55** 2023-08-09 10:19 UTC

**Comment by Jamalam360** [comment] 2023-08-09 11:44
I'll try recreating my config. It might not be getting passed through to Docker properly.

I did give a reason why this message is helpful to me though :-)

**Comment by Jamalam360** [comment] 2023-08-09 11:50
No joy, oh well
